# Variables admin_user, admin_pass, and admin_sshkey need to be set in the
# playbook calling the role. The folder ssh_keys/ needs to contain the
# public keys referenced
---
- name: Adding group ssh
  group:
    name=ssh
    state=present
- name: Adding {{ admin_user }}
  user:
    name={{ admin_user }}
    groups=sudo,ssh
    append=yes
    password={{ admin_pass }}
