- name: Installing NGINX
  apt: pkg=nginx state=installed update_cache=false
  notify:
    - start nginx
- name: Configuring NGINX Virtual Hosts
  template:
    src: hidden_service.j2
    dest: /etc/nginx/sites-available/hidden_service
    backup: yes
    owner: root
    group: root
    mode: "0644"
- name: Removing default sites-enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
- name: Creating new sites-enabled
  file: src=/etc/nginx/sites-available/hidden_service dest=/etc/nginx/sites-enabled/hidden_service state=link
  notify: reload nginx
- name: Launch site
  copy:
    src={{ user_html }}
    dest="/var/www/html/"
